### ISSUE TITLE
Check if species with records outside of australia are thought to be invasive there METHOD 2: 10 species

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/australian_plant_endemism#4]
Method 2 is from iNaturalist

**Comment by wcornwell** [comment]
background reading: https://environmentalcomputing.net/data-manipulation/combining-datasets/

**Comment by stephwoolley** [comment]
Is this the correct one to join or am I joining the initial dataset without the added countries present?  

Joined the natives(wcountries) and invasive (from inaturalist) datasets:
<img width="907" alt="Screen Shot 2022-06-15 at 10 42 42 am" src="https://user-images.githubusercontent.com/106574502/173717533-62f98607-c911-42a9-a79e-b7c9fdeb8214.png">

**Comment by wcornwell** [comment]
looks good to me!  did you push the code that joins them?

**Comment by stephwoolley** [comment]
I tried but for some reason the code isn't appearing when I upload the script

**Comment by wcornwell** [comment]
hmmm...make sure you save locally the script locally first?

**Comment by stephwoolley** [comment]
ahh yep I think it should be fixed now!
